# specify the scope (project/folder/organization) :
# - projects/{PROJECT_ID} (e.g., "projects/foo-bar")
# - projects/{PROJECT_NUMBER} (e.g., "projects/12345678")
# - folders/{FOLDER_NUMBER} (e.g., "folders/1234567")
# - organizations/{ORGANIZATION_NUMBER} (e.g., "organizations/123456")
scope: "projects/burner-aayvyas"
query:
orderBy:
# specify the name of resources/assets that you want to exclude from the report
excludedAssetTypes:
  - "serviceusage.googleapis.com/Service"
# all supported types: https://cloud.google.com/asset-inventory/docs/supported-asset-types
# Please don't modify the below list unless a supported type is present in the above link and not here.
supportedAssetTypes:
  - "identity.accesscontextmanager.googleapis.com/AccessLevel"
  - "identity.accesscontextmanager.googleapis.com/AccessPolicy"
  - "identity.accesscontextmanager.googleapis.com/ServicePerimeter"
  - "anthos.googleapis.com/ConnectedCluster"
  - "apigateway.googleapis.com/Api"
  - "apigateway.googleapis.com/ApiConfig"
  - "apigateway.googleapis.com/Gateway"
  - "apikeys.googleapis.com/Key"
  - "appengine.googleapis.com/Application"
  - "appengine.googleapis.com/Service"
  - "appengine.googleapis.com/Version"
  - "memcache.googleapis.com/Instance"
  - "artifactregistry.googleapis.com/DockerImage"
  - "artifactregistry.googleapis.com/Repository"
  - "assuredworkloads.googleapis.com/Workload"
  - "gkebackup.googleapis.com/Backup"
  - "gkebackup.googleapis.com/BackupPlan"
  - "gkebackup.googleapis.com/Restore"
  - "gkebackup.googleapis.com/RestorePlan"
  - "gkebackup.googleapis.com/VolumeBackup"
  - "gkebackup.googleapis.com/VolumeRestore"
  - "beyondcorp.googleapis.com/AppConnection"
  - "beyondcorp.googleapis.com/AppConnector"
  - "beyondcorp.googleapis.com/AppGateway"
  - "beyondcorp.googleapis.com/ClientConnectorService"
  - "beyondcorp.googleapis.com/ClientGateway"
  - "bigquery.googleapis.com/Dataset"
  - "bigquery.googleapis.com/Model"
  - "bigquery.googleapis.com/Table"
  - "privateca.googleapis.com/CaPool"
  - "privateca.googleapis.com/Certificate"
  - "privateca.googleapis.com/CertificateAuthority"
  - "privateca.googleapis.com/CertificateRevocationList"
  - "privateca.googleapis.com/CertificateTemplate"
  - "bigtableadmin.googleapis.com/AppProfile"
  - "bigtableadmin.googleapis.com/Backup"
  - "bigtableadmin.googleapis.com/Cluster"
  - "bigtableadmin.googleapis.com/Instance"
  - "bigtableadmin.googleapis.com/Table"
  - "cloudbilling.googleapis.com/BillingAccount"
  - "cloudbilling.googleapis.com/ProjectBillingInfo"
  - "composer.googleapis.com/Environment"
  - "datafusion.googleapis.com/Instance"
  - "dlp.googleapis.com/DeidentifyTemplate"
  - "dlp.googleapis.com/DlpJob"
  - "dlp.googleapis.com/InspectTemplate"
  - "dlp.googleapis.com/JobTrigger"
  - "dlp.googleapis.com/StoredInfoType"
  - "dns.googleapis.com/ManagedZone"
  - "dns.googleapis.com/Policy"
  - "domains.googleapis.com/Registration"
  - "cloudfunctions.googleapis.com/CloudFunction"
  - "cloudfunctions.googleapis.com/Function"
  - "healthcare.googleapis.com/ConsentStore"
  - "healthcare.googleapis.com/Dataset"
  - "healthcare.googleapis.com/DicomStore"
  - "healthcare.googleapis.com/FhirStore"
  - "healthcare.googleapis.com/Hl7V2Store"
  - "ids.googleapis.com/Endpoint"
  - "cloudkms.googleapis.com/CryptoKey"
  - "cloudkms.googleapis.com/CryptoKeyVersion"
  - "cloudkms.googleapis.com/EkmConnection"
  - "cloudkms.googleapis.com/ImportJob"
  - "cloudkms.googleapis.com/KeyRing"
  - "logging.googleapis.com/LogBucket"
  - "logging.googleapis.com/LogMetric"
  - "logging.googleapis.com/LogSink"
  - "monitoring.googleapis.com/AlertPolicy"
  - "run.googleapis.com/DomainMapping"
  - "run.googleapis.com/Execution"
  - "run.googleapis.com/Job"
  - "run.googleapis.com/Revision"
  - "run.googleapis.com/Service"
  - "spanner.googleapis.com/Backup"
  - "spanner.googleapis.com/Database"
  - "spanner.googleapis.com/Instance"
  - "sqladmin.googleapis.com/BackupRun"
  - "sqladmin.googleapis.com/Instance"
  - "storage.googleapis.com/Bucket"
  - "tpu.googleapis.com/Node"
  - "compute.googleapis.com/Autoscaler"
  - "compute.googleapis.com/Address"
  - "compute.googleapis.com/BackendBucket"
  - "compute.googleapis.com/BackendService"
  - "compute.googleapis.com/Commitment"
  - "compute.googleapis.com/Disk"
  - "compute.googleapis.com/ExternalVpnGateway"
  - "compute.googleapis.com/Firewall"
  - "compute.googleapis.com/FirewallPolicy"
  - "compute.googleapis.com/ForwardingRule"
  - "compute.googleapis.com/HealthCheck"
  - "compute.googleapis.com/HttpHealthCheck"
  - "compute.googleapis.com/HttpsHealthCheck"
  - "compute.googleapis.com/Image"
  - "compute.googleapis.com/Instance"
  - "compute.googleapis.com/InstanceGroup"
  - "compute.googleapis.com/InstanceGroupManager"
  - "compute.googleapis.com/InstanceTemplate"
  - "compute.googleapis.com/Interconnect"
  - "compute.googleapis.com/InterconnectAttachment"
  - "compute.googleapis.com/License"
  - "compute.googleapis.com/Network"
  - "compute.googleapis.com/NetworkEndpointGroup"
  - "compute.googleapis.com/NodeGroup"
  - "compute.googleapis.com/NodeTemplate"
  - "compute.googleapis.com/PacketMirroring"
  - "compute.googleapis.com/Project"
  - "compute.googleapis.com/Reservation"
  - "compute.googleapis.com/ResourcePolicy"
  - "compute.googleapis.com/Route"
  - "compute.googleapis.com/Router"
  - "compute.googleapis.com/SecurityPolicy"
  - "compute.googleapis.com/Snapshot"
  - "compute.googleapis.com/SslCertificate"
  - "compute.googleapis.com/SslPolicy"
  - "compute.googleapis.com/Subnetwork"
  - "compute.googleapis.com/ServiceAttachment"
  - "compute.googleapis.com/TargetHttpProxy"
  - "compute.googleapis.com/TargetHttpsProxy"
  - "compute.googleapis.com/TargetInstance"
  - "compute.googleapis.com/TargetPool"
  - "compute.googleapis.com/TargetTcpProxy"
  - "compute.googleapis.com/TargetSslProxy"
  - "compute.googleapis.com/TargetVpnGateway"
  - "compute.googleapis.com/UrlMap"
  - "compute.googleapis.com/VpnGateway"
  - "compute.googleapis.com/VpnTunnel"
  - "datamigration.googleapis.com/ConnectionProfile"
  - "datamigration.googleapis.com/MigrationJob"
  - "dataflow.googleapis.com/Job"
  - "dataplex.googleapis.com/Asset"
  - "dataplex.googleapis.com/Lake"
  - "dataplex.googleapis.com/Task"
  - "dataplex.googleapis.com/Zone"
  - "dataproc.googleapis.com/AutoscalingPolicy"
  - "dataproc.googleapis.com/Batch"
  - "dataproc.googleapis.com/Cluster"
  - "dataproc.googleapis.com/Job"
  - "dataproc.googleapis.com/WorkflowTemplate"
  - "metastore.googleapis.com/Backup"
  - "metastore.googleapis.com/MetadataImport"
  - "datastream.googleapis.com/ConnectionProfile"
  - "datastream.googleapis.com/PrivateConnection"
  - "datastream.googleapis.com/Stream"
  - "dialogflow.googleapis.com/Agent"
  - "dialogflow.googleapis.com/LocationSettings"
  - "dialogflow.googleapis.com/ConversationProfile"
  - "dialogflow.googleapis.com/KnowledgeBase"
  - "documentai.googleapis.com/HumanReviewConfig"
  - "documentai.googleapis.com/LabelerPool"
  - "documentai.googleapis.com/Processor"
  - "documentai.googleapis.com/ProcessorVersion"
  - "eventarc.googleapis.com/Trigger"
  - "file.googleapis.com/Backup"
  - "file.googleapis.com/Instance"
  - "file.googleapis.com/Snapshot"
  - "firebase.googleapis.com/FirebaseAppInfo"
  - "firebase.googleapis.com/FirebaseProject"
  - "firestore.googleapis.com/Database"
  - "gameservices.googleapis.com/GameServerCluster"
  - "gameservices.googleapis.com/GameServerConfig"
  - "gameservices.googleapis.com/GameServerDeployment"
  - "gameservices.googleapis.com/Realm"
  - "container.googleapis.com/Cluster"
  - "container.googleapis.com/NodePool"
  - "extensions.k8s.io/Ingress"
  - "networking.k8s.io/Ingress"
  - "apps.k8s.io/Deployment"
  - "apps.k8s.io/ReplicaSet"
  - "batch.k8s.io/Job"
  - "k8s.io/Node"
  - "k8s.io/Namespace"
  - "k8s.io/Pod"
  - "k8s.io/Service"
  - "networking.k8s.io/NetworkPolicy"
  - "rbac.authorization.k8s.io/ClusterRole"
  - "rbac.authorization.k8s.io/ClusterRoleBinding"
  - "rbac.authorization.k8s.io/Role"
  - "rbac.authorization.k8s.io/RoleBinding"
  - "clouddeploy.googleapis.com/DeliveryPipeline"
  - "clouddeploy.googleapis.com/Release"
  - "clouddeploy.googleapis.com/Rollout"
  - "clouddeploy.googleapis.com/Target"
  - "gkehub.googleapis.com/Membership"
  - "gkehub.googleapis.com/Feature"
  - "iam.googleapis.com/Role"
  - "iam.googleapis.com/ServiceAccount"
  - "iam.googleapis.com/ServiceAccountKey"
  - "connectors.googleapis.com/Connection"
  - "managedidentities.googleapis.com/Domain"
  - "redis.googleapis.com/Instance"
  - "networkconnectivity.googleapis.com/Hub"
  - "networkconnectivity.googleapis.com/Spoke"
  - "networkmanagement.googleapis.com/ConnectivityTest"
  - "networkservices.googleapis.com/EndpointPolicy"
  - "networkservices.googleapis.com/Gateway"
  - "networkservices.googleapis.com/GrpcRoute"
  - "networkservices.googleapis.com/HttpRoute"
  - "networkservices.googleapis.com/Mesh"
  - "networkservices.googleapis.com/ServiceBinding"
  - "networkservices.googleapis.com/TcpRoute"
  - "networkservices.googleapis.com/TlsRoute"
  - "orgpolicy.googleapis.com/Policy"
  - "orgpolicy.googleapis.com/Policy"
  - "pubsub.googleapis.com/Snapshot"
  - "pubsub.googleapis.com/Subscription"
  - "pubsub.googleapis.com/Topic"
  - "cloudresourcemanager.googleapis.com/Folder"
  - "cloudresourcemanager.googleapis.com/Organization"
  - "cloudresourcemanager.googleapis.com/Project"
  - "secretmanager.googleapis.com/Secret"
  - "secretmanager.googleapis.com/SecretVersion"
  - "vpcaccess.googleapis.com/Connector"
  - "servicedirectory.googleapis.com/Namespace"
  - "servicemanagement.googleapis.com/ManagedService"
  - "serviceusage.googleapis.com/Service"
  - "speech.googleapis.com/CustomClass"
  - "speech.googleapis.com/PhraseSet"
  - "transcoder.googleapis.com/Job"
  - "transcoder.googleapis.com/JobTemplate"
  - "aiplatform.googleapis.com/BatchPredictionJob"
  - "aiplatform.googleapis.com/CustomJob"
  - "aiplatform.googleapis.com/DataLabelingJob"
  - "aiplatform.googleapis.com/Dataset"
  - "aiplatform.googleapis.com/Endpoint"
  - "aiplatform.googleapis.com/Featurestore"
  - "aiplatform.googleapis.com/HyperparameterTuningJob"
  - "aiplatform.googleapis.com/MetadataStore"
  - "aiplatform.googleapis.com/Model"
  - "aiplatform.googleapis.com/ModelDeploymentMonitoringJob"
  - "aiplatform.googleapis.com/PipelineJob"
  - "aiplatform.googleapis.com/SpecialistPool"
  - "aiplatform.googleapis.com/Tensorboard"
  - "aiplatform.googleapis.com/TrainingPipeline"
